-- Create databases
CREATE DATABASE IF NOT EXISTS BT_AUTH;
CREATE DATABASE IF NOT EXISTS BT_TOUR;

-- Grant privileges
GRANT ALL PRIVILEGES ON BT_AUTH.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON BT_TOUR.* TO 'root'@'%';
FLUSH PRIVILEGES;