-- Create databases
CREATE DATABASE IF NOT EXISTS BT_AUTH;
CREATE DATABASE IF NOT EXISTS BT_TOUR;
CREATE DATABASE IF NOT EXISTS BT_BOOKING;
CREATE DATABASE IF NOT EXISTS BT_PAYMENT;

-- Grant privileges
GRANT ALL PRIVILEGES ON BT_AUTH.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON BT_TOUR.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON BT_BOOKING.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON BT_PAYMENT.* TO 'root'@'%';
FLUSH PRIVILEGES;