CREATE DATABASE IF NOT EXISTS BT_AUTH CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS BT_TOUR CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS BT_PAYMENT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;